-- Internship Applications Table
CREATE TABLE IF NOT EXISTS internship_applications (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    mobile VARCHAR(50) NOT NULL,
    dob DATE NOT NULL,
    gender ENUM('Male', 'Female', 'Other') NOT NULL,
    qualification VARCHAR(255) NOT NULL,
    university VARCHAR(255) NOT NULL,
    department ENUM('IT', 'Finance', 'Admin') NOT NULL,
    internship_coordinator VARCHAR(255),
    hours INT,
    joining_date DATE,
    disability ENUM('Yes', 'No') DEFAULT 'No',
    disability_type VARCHAR(255),
    place VARCHAR(255),
    resume_url TEXT,
    stage ENUM('Applied', 'Interview', 'Accepted', 'Rejected', 'Completion', 'Certification') DEFAULT 'Applied',
    interview_date DATETIME,
    interview_venue VARCHAR(255),
    interview_time TIME,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_stage (stage),
    INDEX idx_department (department),
    INDEX idx_email (email),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
